### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by akinsho** [vim-test/vim-test#209]
Hi, thanks for the excellent plugin which is amazing and works  really well with my javascript,

I'm currently working a lot more with typescript and have been playing with tweaking the javascript runner to work with typescript with no success. As far as I can tell what would be needed for this plugin to work with typescript would be to have the same set of runners as for JS but pass an argument somehow to point vim test to the typescript compiler's output directory. To run the tests on the JS that it compiles. I've tried creating a runner by duplicating the JS ones (which might be the wrong track) but I can't figure out how to point the plugin at a directory which is a variable or how it might recognise a TS file without a new runner for typescript. 

I'd love some advice and am happy to put in some leg work myself to add this runner.

**Comment by codeinabox** [comment]
That would be great to add Typescript support. Could you please link to some documentation for the runner you would like to add and I'll advise as best as I can.

**Comment by Akin909** [comment]
Hi, Thanks for the speedy response, what I sort of envisioned was for a typescript runner or flag to basically just run the javascript runner so the ts one would just redirect vim-test to the a directory a user could specify because all the runners for javascript are valid for typescript as far as I know, so rather than having to constantly update the TS runners and JS runners separately if the JS runners got updated then you could just use the new js one. Not that I know how that can be done 😨 , the runners I had in mind were at least [jest](https://github.com/facebook/jest/tree/master/examples/typescript) and [mocha](https://mochajs.org/). To use these in a normal ts project you would usually just configure them in the package json so stuff like calling the compiler could be left to those libraries maybe

**Comment by codeinabox** [comment]
Perhaps the simplest solution might be a strategy

**Comment by codeinabox** [comment]
To clarify are your tests written in JavaScript or TypeScript?

**Comment by Akin909** [comment]
Tests are written in typescript which is compiled to javascript by the ts compiler, both jest and mocha run those. As for using a strategy Im not sure how to trigger a strategy for a file type that the plugin doesn't recognise, if I could invoke the plugin in a typescript file then if it runs mocha or jest commands they should both be able to manage the rest.

**Comment by codeinabox** [comment]
I see your point. Given the way the plugin works, you would have to duplicate the existing JavaScript runners to make TypeScript versions. I don't think this can be avoided as they have different file types and the runner detection is based on that. @janko-m what are your thoughts?

In regards to your initial question, why does it need to point to the compiler's output directory? The examples I seen for using Mocha with TypeScript still run against the TS files https://journal.artfuldev.com/write-tests-for-typescript-projects-with-mocha-and-chai-in-typescript-86e053bdb2b6

**Comment by Akin909** [comment]
My thinking there was that in that case the "typescript" runner would basically be a special call of the javascript runner that only looked inside of a given directory or range of directories like 'build' etc that the user could supply in their vimrc (less than ideal I realise since these names could vary a great deal per project) , but I think that that would still require the plugin to recognise typescript in which case just using the default commands for mocha etc. would be better

**Comment by janko-m** [comment]
@Akin909 If I understood correctly, something else will be doing the TypeScript => JavaScript compilation, not the test runner? Because I see for example `mocha` supporting the `--compilers` option, and I know it works for CoffeeScript, maybe it works for TypeScript as well? Or were you hoping for a generic solution, where you would be able to run TypeScript test files even with test frameworks that don't support on-the-fly compilation?

Since you've proposed the latter, let's discuss that. As I see it, it would be hard for test.vim to automatically determine the compilation directory (because it's configured by the user), so it would have to be configured manually. The easiest way that I see it is to add support to every test.vim runner for `.ts` files, and then write a **transformation** that will replace the `.ts` file with the correct `.js` file.

For example, let's say that a TypeScript file is in the `test/` directory, and you want to reference the compiled JavaScript file in the `build/test` directory. The following transformation should do it, provided that test.vim runner is already updated to support `.ts` files (though I didn't test it):

```vim
" this can be in the project-local .vimrc
function! TypeScriptTransform(cmd) abort
  return substitute(a:cmd, '\vtest/(\S+)\.ts', 'build/test/\1.js')
endfunction

let g:test#custom_transformations = {"typescript" => "TypeScriptTransform"}
let g:test#transformation = "typescript"
```

**Comment by Akin909** [comment]
@janko-m  typescript is compiled by the typescript compiler to JS which most test runners need to be pointed at, I personally have not used the compilers option as I can usually just point the runner at the output directory, either way I think rather than thinking too much about compilation if it was possible to run mocha or jest potentially with flags inside of a ts/tsx file in vim that would be enough because most test runners for ts/js have some process for running ts test files. 

Ill have a go with the transformation, thanks!

**Comment by Akin909** [comment]
Hi sorry for the late response I only now just got round to testing the transformation, after adding `ts` and `tsx` to the `js` regexps the command correctly looks for the associated ts file and runs the built test 👍. I wonder if it would be worth adding a section to the readme for ts, and maybe adding `ts` and `tsx` to the [Javascript regular expressions](https://github.com/janko-m/vim-test/blob/c60a0e2679ecde4a929cbabf6573ba67524f1adf/autoload/test/javascript/mocha.vim#L2) that way a user can just create a per project transformation based on a readme example

**Comment by codeinabox** [comment]
Having started on a TypeScript project this would be handy, effectively you'd just want to apply the transformation for only certain file types.

**Comment by gunar** [comment]
I got it to work like this:

```vim
" --- {{{ TypeScript
let g:test#javascript#mocha#file_pattern = '\v.*\.spec\.(ts|tsx)$'
function! TypeScriptTransform(cmd) abort
  return substitute(a:cmd, '\v(.*)mocha', 'TS_NODE_FILES=true \1ts-mocha', '')
endfunction
let g:test#custom_transformations = {'typescript': function('TypeScriptTransform')}
let g:test#transformation = 'typescript'
" --- }}}

```

PS: Uses `ts-mocha`.

**Comment by andys8** [comment]
I'm using `typescript` and `create-react-app` (`react-scripts`). So jest is used, but the `matchPattern` doesn't look right.

```shell
node_modules/.bin/jest --no-coverage -- src/auth.test.ts
No tests found
In /home/qw/dev/repository/project/
  42 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 42 matches
Pattern: src/auth.test.ts - 0 matches

shell returned 1

Press ENTER or type command to continue
```

But this looks promising: https://github.com/janko/vim-test/blob/master/autoload/test/javascript/jest.vim#L2

I think it could be caused, because there is no direct dependency to `jest`.

**Comment by jtumano** [comment]
in my Vue project with Typescript I had `ts-jest` dependency instead of `jest` and it was not detected. 
I've made a simple change which helped: https://github.com/jtumano/vim-test/commit/1e8713f39d6a2dbc62d1863195ec4494aaaa9b18 

@janko  Currently I don't know what should be correct way to fix better - maybe to separate these runners to Jest and TsJest, so file patterns should be also fixed. Or leave it as is and to create a pull-request? But in this case tests should be also improved acc to this functionality

**Comment by fnune** [comment]
How can I help push the development of this?

**Comment by VVKot** [comment]
I made it work for my project by executing the `jest` in the context of directory containing the test. As far as I can tell, this is because jest can recursively find jest config/tsconfig up the tree and sort itself out. This is even more useful to those who develop in monorepos/repos with non-standard layout. Only you can tell if that's madness or brilliance - but it works for me!

The gist is temporarily setting `cwd` using `autochdir` (using current file's path would work too, I just didn't bother with path parsing) AND changing it back afterwards. Remembering that changed path allows to wrap `TestLast` / `TestVisit` so that they continue to work.
https://github.com/VVKot/dotfiles/blob/fbba7bb7ded44b0ff336e6233a7029b79eeff54a/config/nvim/lua/plugin/vim-test.lua#L1-L31

P.S. Not sure if people in this thread are having the same problem. The above only applies if running `jest .` (or equivalent) in the directory containing the test completes successfully for you. It assumes that you already executed a build command before that transpiled your Typescript code to Javascript.

**Comment by Lilja** [comment]
Perhaps some (initial?) typescript can be done with `yarn`/`ts-mocha`/`ts-jest` support? I understand there is pain that a lot of config is shared between node/typescript runners but perhaps only using `ts-*` as runner is decent trade off?

Typescript is getting bigger every year and more and more projects are using it natively. This issue has been open for quite some years now and it would be great if we have another look at this. I would like to volunteer, but it doesn't look like the main maintainer is too active since 2020.

**Comment by janko** [comment]
@Lilja While I don't have time to contribute to vim-test anymore, I will happily merge any improvements to TypeScript support that is documented, requires zero or minimal amount of configuration, and retains backwards compatibility. Just please @mention me in the PR, as I'm not subscribed to the repository anymore.

**Comment by codeinabox** [comment]
Going to close this as TypeScript support has since been added for many JS runners. Feel free to reopen if there are any runners that still need to be updated.
