### ISSUE TITLE
ruby#cucumber runner unusable if features directory is not in the root.

### ISSUE THREAD

**Issue by benwainwright** [vim-test/vim-test#327]
Hi there

I installed `vim-test` on a recommendation by a colleague that has had it a while. Unfortunately, whenever I tried to run cucumber tests on a `.feature` file, I got an error message, claiming that it was 'not a test file'.

Mystified, I did a little digging around your codebase and came across the source of the problem. Pull request https://github.com/janko-m/vim-test/pull/286 renders this plugin unusable in the following situation:

- You want to run cucumber tests
- Cucumber related ruby files are not stored within `<project_root>/features`

This renders your plugin unusable for pretty much our entire legacy codebase: of the 6 repositories containing cucumbers that I currently have checked out on my work laptop, not a single one of them has a features directory in the project root, and moving directories around in large legacy projects is not a trivial change, and certainly not one that is going to be sanctioned.

I'm happy to attempt to come up with a patch that solves this problem, but I wanted to hear your thoughts on the two potential solutions:

- In the PR that introduced this change, it notes that "The existing setup had Ruby as the "default" runner for .feature files". I don't see why this is a problem; **ruby** is a sensible default given its wide use, and it is just one line of configuration in the `.vimrc` file to change this. Surely this is better than pretty much breaking the plugin for _a lot_ of ruby/cucumber users?
- If you don't agree with this, my alternative suggestion is changing the glob that is part of `test#javascript#cucumberjs#test_file` to a function that searches directories below the feature file first, then in its parent directory, then the directory above it, then above that and so on until you reach the project directory. This approach would probably be more efficient than globbing the entire feature directory anyway, and would allow for alternative directory structures.

**Comment by janko-m** [comment]
I 👍 your second solution, though I would propose a slight modification:

Search for the `features/` directory starting from the file's directory upwards, and once you find it, glob that directory recursively for `*.rb` files. We do still need to recursively search for Ruby files, because `env.rb` is commonly found in `features/support/env.rb`.

Then we could apply the same thing to CucumberJS and Behat. I don't think it's necessary to make Ruby the default and require explicit configuration in `.vimrc` for other languages, because we should be able to support your use case while still keeping the language auto-detected.

**Comment by benwainwright** [comment]
Thanks for your quick response. Expect a PR in the next few weeks :)
