### ISSUE TITLE
New php test runner for Laravel 7

### ISSUE THREAD

**Issue by rodrigore** [vim-test/vim-test#445]
Hi, This week Laravel 7 will be launch with a new command called for testing `php artisan test` which has a pretty looking good output.

Just for testing I modified the *phpunit.vim* file and inside the executable method I added this condition in order to try the new command:
``` vim
function! test#php#phpunit#executable() abort
  if filereadable('vendor/nunomaduro/collision/phpunit.xml.dist')
    return 'php artisan test'
  elseif ...
```

And it works. Here is an output 

![image](https://user-images.githubusercontent.com/1557305/75742814-941aa480-5ced-11ea-86ca-6e8920408a82.png)

I'm not entirely familiar the way to add another runner for laravel 7 or if maybe my solution works fine for all the project and I only should to make a pull request to add that line.

Hope if anyone can guide me, thank you!

**Comment by codeinabox** [comment]
Thank you for the heads up. I just had look into the documentation for version 7 and it uses phpunit under the hood so this feels like like an alternate run command for the phpunit runner rather than a whole new runner making this is quite similar to #424.

Can you try using `let test#php#phpunit#executable = 'php artisan test'` for now and if that works I am happy to make the changes myself

**Comment by rodrigore** [comment]
Thanks for helping me so fast and the command `let test#php#phpunit#executable = 'php artisan test'`  it works 😄

**Comment by codeinabox** [comment]
Great. Does it accept all the same arguments as phpunit?

**Comment by rodrigore** [comment]
@codeinabox  yes, is the same

**Comment by codeinabox** [comment]
Excellent. When I get time I will create a branch and PR you can test with.

**Comment by codeinabox** [comment]
@rodrigore I've created a new branch you can test against, please let me know how you get on

**Comment by rodrigore** [comment]
@codeinabox thank you! I tested and work fine

**Comment by lukestorms** [comment]
Hi, I just wanted to comment on this. The `test` command in `php artisan test` is not provided by Laravel but by a third party package: https://github.com/nunomaduro/collision. While it is true that new Laravel projects have this package added by default, it is optional, and projects that have upgraded from an earlier version (or removed it manually) will not have a `test` command, and the phpunit runner is now failing.

I've got around this by manually resetting the phpunit executable:
```vim
let test#php#phpunit#executable = './vendor/bin/phpunit'
```
but that seems a bit backwards given that I was expecting it to use phpunit by default.

Another way around this, while keeping this a part of the phpunit runner, is by updating the executable function to check if the "nunomaduro/collision" is installed:

1. by checking the package is a dependency
```vim
function! test#php#phpunit#executable() abort
  if filereadable('./artisan') 
        \ && filereadable('composer.json')
        \ && !empty(filter(readfile('composer.json'), 'v:val =~# "nunomaduro/collision"'))
    return 'php artisan test'
  elseif ...
```
2. or by checking the folder exists:
```vim
function! test#php#phpunit#executable() abort
  if filereadable('./artisan') && isdirectory('./vendor/nunomaduro/collision')
    return 'php artisan test'
  elseif ...
```

I'm sure not many people are impacted by this, for now I'm satisfied with manually setting my phpunit executable.

**Comment by codeinabox** [comment]
Thank you for investigating this, I did not realise that the artisan test command was optional. Based on what you've told me I feel there are two options in this case:

1. Introduce the additional checks that `nunomaduro/collision` is installed
2. Remove the logic and require users to override the executable using `let test#php#phpunit#executable = 'php artisan test'`

I don't mind either but I am not a Laravel user so if you two could indicate which one you think is most maintainable please let me know and I will implement.

**Comment by lukestorms** [comment]
I think it would be better to require users to override the executable, but I do admit that it would not be obvious that the executable could be set to `php artisan test` without someone finding this issue or some mention of it in the docs.

The `nunomaduro/collision` package seems fairly stable and has been around for a few years; I doubt it would go away. If Laravel were to remove the package from the default install in the future, `php artisan test` would still work (if `nunomaduro/collision` was manually installed) because it auto-registers itself.

With that being said I had not heard of this package until I started looking into this issue, and I suppose it would open the door to requests for other wrappers (if there are any) being handled here as well.

**Comment by codeinabox** [comment]
There is support for the alternate PHPUnit runner [ParaTest](https://github.com/paratestphp/paratest) though that is trivial as it just involves checking for the presence of it in the vendor bin directory.

I had a look at `nunomaduro/collision` and it doesn't have its own binary, in fact you use it by adding it to phpunit.xml.

My gut feeling is it makes more sense for the user to override the executable or update their phpunit.xml file. @rodrigore any objections to this?

**Comment by rodrigore** [comment]
I dont have any objections

**Comment by codeinabox** [comment]
This functionality has been removed so now you need to use `let test#php#phpunit#executable = 'php artisan test'`
