### ISSUE TITLE
strategy asyncrun_background in the quickfix has syntax highlight colours missing :(

### ISSUE THREAD

**Issue by chris542** [vim-test/vim-test#531]
I've been using 'vimterminal' as my strategy until i found out that i can use 'asyncrun_background'

I've got everything set up nicely so it's looking very good!

But I just realised when strategy is in the quickfix, you no longer see the colours :( 

![image](https://user-images.githubusercontent.com/17423698/100513865-14b2f680-31d5-11eb-903d-c634e88f77f5.png)
![image](https://user-images.githubusercontent.com/17423698/100513871-1e3c5e80-31d5-11eb-9b72-05aae0464a0f.png)

**Comment by codeinabox** [comment]
I don't think ANSI colours are supported in quickfix https://vi.stackexchange.com/questions/3250/showing-colors-in-vims-quickfix-window-from-dispatch-tasks

**Comment by chris542** [comment]
@codeinabox it actually works when i force jest to print with colors using--colors flag. But it prints ANSI code that looks like [<33Er etc. 

I tried installing ANSIEsc vim plugin which does resolve this issue but i has to call :ANSIEsc whenever i needed the color syntax which is annoying. There was a way to call out whenever i start vim but unfortunately:ANSIEsc only provides 'toggle' so whenever i save vimrc, it calls the method again and turns off the syntax highlight

It definitely works but i just can't find the best way to always encode ANSI codes

**Comment by trisys3** [comment]
Even with `AnsiEsc`, the double pipe is still output at the beginning, which doesn't happen in the location list.

**Comment by trisys3** [comment]
Regarding running `AnsiEsc` when the quickfix list is opened, this is what I came up with:

```
au BufWinEnter quickfix call OnFirstQfOpen()

let g:quickOpened = 1
function OnFirstQfOpen()
    if g:quickOpened != 1
        let g:quickOpened = 1
        AnsiEsc
    endif
endfunction
```

This also avoids calling `AnsiEsc` again if the quickfix window was already opened in the past, as the state of the quickfix survives closing and there is only a toggle for `AnsiEsc`, not one command for "on" and another command for "off". I'm not sure if the quickfix window can actually be destroyed without closing `vim`, but if so that should be an easy fix.

Huge thanks to [this StackOverflow question](https://vi.stackexchange.com/questions/14065/autocmd-with-quickfix-window#answer-19048), which got me on the right track.
